Add controllers
PavlovILYA/share-it pull request #1
Opened 2022-08-19 16:29 UTC by PavlovILYA

2022-08-22 12:31 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto saveItem(@RequestHeader("X-Sharer-User-Id") Long userId,
хедер стоит вынести в константы

2022-08-22 12:32 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemService.saveItem(itemDto, userId);
лучше сделать, чтобы сервис отдавал сервисные объекты Item, а в контроллере уже мапить в ItemDto

этот сервис может понадобиться в другом сервисе и там dto объект будет выглядеть странно

2022-08-22 12:34 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (itemDto.getName() != null && itemDto.getName().isBlank()
стоит вынести в отдельный метод `validate(ItemDto itemDto)`

и на каждый кейс выбрасывать исключение с разным сообщением

2022-08-22 12:59 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/exception/WrongItemOwnerException.java
> +public class WrongItemOwnerException extends RuntimeException {
привычнее название будет `InvalidOwnerException`

2022-08-22 12:59 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/exception/WrongItemOwnerException.java
> +public class WrongItemOwnerException extends RuntimeException {
но это вкусовщина, остается на усмотрение студента

2022-08-22 13:00 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return ItemMapper.toItemDto(itemRepository.get(itemId));
стоит мапить на уровне контроллера

2022-08-22 13:01 UTC, makholin commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private LocalDateTime created;
created больше подходит для булеан типа
лучше createdAt, но если на это завязаны тесты постмана, то можно оставить

2022-08-22 13:02 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/repository/FakeUserRepositoryImpl.java
> +public class FakeUserRepositoryImpl implements UserRepository {
лучше назвать `InMemoryUserRepository`

2022-08-22 13:03 UTC, makholin requested changes
Нужно исправить замечания

2022-08-24 07:34 UTC, PavlovILYA commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private LocalDateTime created;
К сожалению, влияет на тесты

2022-08-25 00:02 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            errors += "Invalid field 'description' for ItemDto ";
обычно так не делают
правильнее будет 
```
void validate() {
    if (...) throw new Exception("Invalid size");
    if (...) throw new Exception("Unknown id");
}
```

2022-08-25 00:05 UTC, makholin requested changes
нужно исправить метод валидации

2022-08-25 08:36 UTC, PavlovILYA commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            errors += "Invalid field 'description' for ItemDto ";
А я так сделал специально, чтобы сразу все ошибки выводились списком (в таком случае их все можно было бы за раз исправить на стороне клиента)

Переделаю

2022-08-25 08:47 UTC, PavlovILYA commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            errors += "Invalid field 'description' for ItemDto ";
Но, если я не ошибаюсь, при использовании аннотации @Valid все ошибки выводятся разом
(Я пытался сделать так же)

2022-08-25 14:10 UTC, makholin approved these changes
работа принята

2022-08-26 06:33 UTC, merged