Add bookings and comments
PavlovILYA/share-it pull request #2
Opened 2022-09-05 19:11 UTC by PavlovILYA

2022-09-05 19:37 UTC, PavlovILYA commented
Сергей, добрый вечер!

Хочу уточнить у Вас один момент:
В прошлом ревью Вы сказали мне сделать маппинг (из dto в entity) на уровне контроллеров, я последовал совету

Но возникла такая ситуация, что уровни сильно переплелись:
В контроллеры пришлось инжектить несколько сервисов (для маппинга более сложных вложенных dto), хотя до этого момента я всегда старался придерживаться принципа – __*"в каждом контроллере только один соответствующий ему сервис"*__
Правильный ли это вообще принцип? Сейчас он у меня нарушен

Еще на вебинаре наставник сказал нам, что маппинг необходимо проводить в сервисах, дабы максимально упростить (облегчить) контроллеры
И сказал, что ревьюер мог быть не прав
Вот отрывок этого вебинара:
https://disk.yandex.ru/i/yj38Nd2khRJPvA

P.S. На данный момент я провожу маппинг в контроллерах, следуя Вашему совету (но хочу разобраться в том, какой подход все же уместнее)

2022-09-07 10:42 UTC, makholin commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
> +        log.info("404 {}", e.getMessage());
логировать ошибки нужно с уровнем error
и сообщение лучше сделать более информативным

log.error("Response HTTP 404:  {}", e.getMessager)

2022-09-07 10:43 UTC, makholin commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
> +        log.info("400 {}", e.getMessage());
в остальных хендлерах тоже лог стоит исправить

2022-09-07 10:44 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private static final String USER_ID_HEADER = "X-Sharer-User-Id";
константы должны быть первые в списке и отделятся от других полей пустой строкой

2022-09-07 10:45 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingReturnDto.java
> +public class BookingReturnDto {
лучше назвать `BookingResponseDto`

2022-09-07 10:49 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +        switch (stringStatus) {
можно мапить методом BookingStatus.valueOf(stringStatus) вместо switch и метод обернуть в try catch, чтобы  ошибку мапинга словить и выбросить InvalidBookingStatusException

2022-09-07 10:49 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +        if (isApproved) {
можно передавать примитив
и эту конструкцию упростить до 
`return approved ? APPROVED : REJECTED;`

2022-09-07 10:51 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getItem().getAvailable().equals(Boolean.TRUE)) {
лучше избегать if else конструкций, они усложняют код
проще будет
```
if (...) throw new Exception();
return repository.save(booking);
```

2022-09-07 10:54 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemReturnDto.java
> +public class ItemReturnDto {
ItemResponseDto будет правильнее

2022-09-07 10:55 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemReturnDto.java
> +    public static class BookingDto {
удобнее ориентироваться в проекте, где все классы модели хранятся в отдельных файлах

2022-09-07 10:56 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +//    private ItemRequest request;
неиспользуемый код нужно удалить

2022-09-07 10:56 UTC, makholin commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +//    private LocalDateTime created;
тут тоже нужно удалить

2022-09-07 11:01 UTC, makholin requested changes
Нужно исправить замечания

По поводу мапинга:
В целом, оба подхода ок
 Обычно при запросе сначала сразу делают валидацию входных данных в дто модели, потом ее мапят уже в сервисный объект, который уже считается полностью валидным и на уровне сервиса не проверяется.
 Но из-за технических требований к вашему проекту чтобы не добавлять в контроллер кучу зависимостей подход с мапингом в сервисе тоже подходит. 
 Также идея с фасадом, который только мапит объекты и прокидывает их в сервис тоже имеет место быть.

2022-09-07 16:41 UTC, PavlovILYA commented on src/main/java/ru/practicum/shareit/item/dto/ItemReturnDto.java
> +    public static class BookingDto {
Не совсем понял этот момент. Это пакет для dto. Для моделей есть отдельный пакет – там все классы в отдельных файлах

Класс ItemResponseDto.BookingDto используется только внутри класса ItemResponseDto  (и еще в соответствующем маппере). Есть отдельные dto непосредственно для сущности Booking - они находятся в отдельном пакете. Я сделал класс внутренним, чтобы показать, что его не нужно больше нигде использовать

Необходимость в создании ItemResponseDto.BookingDto возникла из-за поля "bookerId", которое в других dto для букинга и названо по-другому и имеет иной тип – такое разнообразие из-за требований тестов

P.S. "Return" уже заменил на "Response" по Вашему совету

2022-09-08 10:05 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemReturnDto.java
> +    public static class BookingDto {
два BookingDto в проекте - не очень хорошо, потому что других программистов это точно будет путать и придется держать в голове всегда, что таких классов два

чем проще устроен код, тем лучше, а внутренние классы простоты не добавляют
но этот момент оставляют на твое усмотрение)

2022-09-08 10:07 UTC, makholin approved these changes
Работа принята

2022-09-08 16:36 UTC, merged